version: '3.9'

services:
  tea:
    container_name: collaboration_frontend
    image: nginx:alpine
    restart: always
    volumes:
      - ./frontend/configs:/etc/nginx/conf.d
      - ./frontend/out:/project
    ports:
      - 3004:80