version: '3.8'
services:
  postgreDB:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=09116903138a
      - POSTGRES_DB=example
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - task_manager
  
  backend:
    build: ./
    restart: always
    ports:
      - '9090:9090'
    depends_on:
      - postgreDB
    networks:
      - task_manager


networks:
  task_manager:
     