name: Backend Deployment for `Develop` branch

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: [self-hosted, develop, backend]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install requirements
        working-directory: backend
        run: go mod download -x

      - name: Build project
        working-directory: backend
        run: go build -o api

      - name: Make API Executable
        working-directory: backend
        run: chmod +x ./api

      - name: Restart api service
        working-directory: backend
        run: python3 ./scripts/setup.py install && python3 ./scripts/setup.py restart
