name: Deployment on `Develop`

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: [self-hosted, develop]

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: action-yarn
        # You may pin to the exact commit or the version.
        # uses: comchangs/action-yarn@e4a1f4800849aa2e73dbc77d872a3c011cdc28d5
        uses: comchangs/action-yarn@v0.1-beta
      - run: cd frontend && yarn build
      - name: Restart docker container
      - run: cd frontend && docker compose down && docker compose up -d
